cache_file: output/translated_blocks.json
docai_location: us
docai_processor_id: 272be2d68ebb4a12
document_class: revtex4-2
figures_dir: output/figures
hallucination_ratio: 3.0
layout: onecolumn
location: global
main_font: UnBatang
max_retries: 3
max_workers: 5
model: gemini-3-flash-preview
output_dir: output
project_id: paper-translator-potion
sans_font: UnDotum
template_file: template.tex.j2
translation_style: 한다체
